# Generated by Django 3.2.7 on 2021-09-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formName', models.CharField(max_length=225)),
                ('formContent', models.TextField()),
            ],
            options={
                'db_table': 'FormsTable',
            },
        ),
    ]
