# Generated by Django 3.2.7 on 2021-09-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_response', models.JSONField()),
            ],
            options={
                'db_table': 'response_table',
            },
        ),
        migrations.CreateModel(
            name='UserForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_user', models.CharField(max_length=225)),
                ('form_name', models.CharField(max_length=225)),
                ('form_description', models.TextField()),
                ('form_content', models.TextField()),
                ('user_responses', models.ManyToManyField(to='userforms.ResponsesData')),
            ],
            options={
                'db_table': 'users_forms',
            },
        ),
    ]
