# Generated by Django 3.2.7 on 2021-09-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userforms', '0002_responsesdata_userforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='userforms',
            name='has_files',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
