# Generated by Django 3.2.6 on 2021-09-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0010_userfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiles',
            name='customerName',
            field=models.CharField(default=21, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfiles',
            name='description',
            field=models.TextField(default=-12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfiles',
            name='projectName',
            field=models.CharField(default=-22, max_length=225),
            preserve_default=False,
        ),
    ]
