# Generated by Django 3.2.8 on 2021-10-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0011_auto_20210904_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('step_name', models.CharField(max_length=225)),
                ('step_count', models.IntegerField()),
                ('step_description', models.TextField()),
                ('step_visibility', models.CharField(max_length=20)),
                ('step_download', models.CharField(max_length=20)),
                ('step_document', models.FileField(upload_to='stepfiles')),
            ],
        ),
    ]
