# Generated by Django 3.2.8 on 2021-11-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepautomationapp', '0012_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('step_document', models.FileField(upload_to='documents')),
                ('notarize', models.CharField(max_length=10)),
                ('apostille', models.CharField(max_length=10)),
            ],
        ),
    ]
